import Providers from '@/app/providers'
import Header from '@/components/header/header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={`${inter.className} dark text-foreground bg-background`}>
        <Providers>
          <div className="min-h-screen flex flex-col items-center container mx-auto max-w-6xl">
            <Header/>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
